version = 5.5.0
archive_dir = /etc/letsencrypt/archive/test-scv.normetales.xyz
cert = /etc/letsencrypt/live/test-scv.normetales.xyz/cert.pem
privkey = /etc/letsencrypt/live/test-scv.normetales.xyz/privkey.pem
chain = /etc/letsencrypt/live/test-scv.normetales.xyz/chain.pem
fullchain = /etc/letsencrypt/live/test-scv.normetales.xyz/fullchain.pem
[renewalparams]
account = 875210cb13dbf76f42f540fade3c66fd
pref_challs = http-01,
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
test-scv.normetales.xyz = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-05-22T10:01:42
